### PR TITLE
Kris

### PR DESCRIPTION
**Pull request by KrisMagat**
Completed:
index.js
App.js
dashboard.js
items.js
APIfunctions.js

### CODE REVIEW

**Review by chdavis0917 — APPROVED** [review]
Looks good to me!

**Comment by TrineMedina** [comment]
Chris said it looks good :)

**Review by TrineMedina — APPROVED** [review]
Thank you to Chris for walking me through this lol

**Review by billums123 — APPROVED** [review]
Fantastic work, just remember to change your <RootDiv> component to a normal html <div> tag in App.js.

Fix App import on index.js.

**Comment by billums123** [comment]
First merge, go team!!!

**Pull request merged**
